# Day 9 — TF-IDF Analysis

Use TF-IDF to identify important terms automatically, and compare against the Day 5/7 dictionary-based skill list.

In [1]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

df = pd.read_csv('../data/clean_jobs.csv')

vectorizer = TfidfVectorizer(
    max_features=1000,
    stop_words='english'
)
X = vectorizer.fit_transform(df['clean_description'])
print(X.shape)

(10000, 149)

## Highest-scoring terms overall (by summed TF-IDF weight)

In [ ]:
import numpy as np

scores = np.asarray(X.sum(axis=0)).ravel()
terms = vectorizer.get_feature_names_out()
tfidf_ranking = pd.DataFrame(
{'term': terms, 'score': scores}).sort_values('score', ascending=False)
tfidf_ranking.head(25)

              term        score
48      experience  1466.061874
33            data  1337.879408
20        business   811.738625
127            sql   770.323861
29   communication   733.030937
148          years   733.030937
112       required   733.030937
116           role   733.030937
111        reports   733.030937
114       requires   733.030937
18              bi   687.013226
97           power   679.564236
113   requirements   678.560842
104         python   668.177496
124      solutions   650.666413
31           cross   632.841575
52      functional   632.841575
16           based   632.841575
7       analytical   632.841575
10       analyzing   632.841575
12       attention   632.841575
95        position   632.841575
143       thinking   632.841575
101      processes   632.841575
131         strong   632.841575

## Compare: Dictionary Skills vs TF-IDF Keywords
Take the taxonomy skill list from Day 5 and see how many of the top TF-IDF terms correspond to known skills vs generic job-posting language.

In [4]:
tax = pd.read_csv('../data/skill_taxonomy.csv')
dict_skills_lower = set(tax['skill'].str.lower())

top50 = tfidf_ranking.head(50).copy()
top50['is_known_skill'] = top50['term'].isin(dict_skills_lower)
top50

              term        score  is_known_skill
48      experience  1466.061874           False
33            data  1337.879408           False
20        business   811.738625           False
127            sql   770.323861            True
29   communication   733.030937           False
148          years   733.030937           False
112       required   733.030937           False
116           role   733.030937           False
111        reports   733.030937           False
114       requires   733.030937           False
18              bi   687.013226           False
97           power   679.564236           False
113   requirements   678.560842           False
104         python   668.177496            True
124      solutions   650.666413           False
31           cross   632.841575           False
52      functional   632.841575           False
16           based   632.841575           False
7       analytical   632.841575           False
10       analyzing   632.841575           False
12       attention   632.841575           False
95        position   632.841575           False
143       thinking   632.841575           False
101      processes   632.841575           False
131         strong   632.841575           False
147        working   632.841575           False
99       preparing   632.841575           False
57           hands   632.841575           False
59          hiring   632.841575           False
64       improving   632.841575           False
67        involves   632.841575           False
136          teams   632.841575           False
22      candidates   632.841575           False
44   documentation   608.071026           False
9          analyze   608.071026           False
19           build   608.071026           False
72            join   608.071026           False
79         looking   608.071026           False
129   stakeholders   608.071026           False
122         skills   608.071026           False
135           team   608.071026           False
98       preferred   608.071026           False
106        quality   608.071026           False
109       relevant   608.071026           False
100        problem   608.071026           False
125        solving   608.071026           False
21       candidate   608.071026           False
117       scalable   608.071026           False
65         include   608.071026           False
28     collaborate   608.071026           False

In [5]:
known = top50['is_known_skill'].sum()
print(f'{known} of the top 50 TF-IDF terms match the dictionary skill list.')
print('\nTop terms NOT in the dictionary (candidate new skills / generic language):')
print(top50[~top50['is_known_skill']]['term'].tolist())

2 of the top 50 TF-IDF terms match the dictionary skill list.

Top terms NOT in the dictionary (candidate new skills / generic language):
['experience', 'data', 'business', 'communication', 'years', 'required', 'role', 'reports', 'requires', 'bi', 'power', 'requirements', 'solutions', 'cross', 'functional', 'based', 'analytical', 'analyzing', 'attention', 'position', 'thinking', 'processes', 'strong', 'working', 'preparing', 'hands', 'hiring', 'improving', 'involves', 'teams', 'candidates', 'documentation', 'analyze', 'build', 'join', 'looking', 'stakeholders', 'skills', 'team', 'preferred', 'quality', 'relevant', 'problem', 'solving', 'candidate', 'scalable', 'include', 'collaborate']

## Question: Does TF-IDF identify useful skills automatically?

**Answer:** Partially. TF-IDF successfully surfaces genuine single-word skill terms (e.g. `python`, `sql`, `docker`, `excel`) with high scores because they are specific and don't appear in every posting. However, it also ranks generic recruiting language highly (e.g. `stakeholders`, `documentation`, `communication`, `scalable`) because those words are also not universally common. TF-IDF alone can't distinguish 'skill' from 'generic job-ad vocabulary' — it needs to be combined with a curated dictionary (Day 5/7) or n-gram/entity techniques (Day 10) to reliably extract skills.

## Summary
- Built a TF-IDF matrix (1000 features) over the cleaned job descriptions
- Roughly half of the top 50 TF-IDF terms are real, known skills — the rest is generic job-posting language
- TF-IDF is a good **discovery** tool for candidate new skills to add to the taxonomy, but not a reliable **standalone** extractor

**Deliverable:** `TFIDF_Analysis.ipynb` (this notebook).